# Initial Data Exploration

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

datos = pd.read_csv('../data/bronze/casas_gam_full2.csv')
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Total_area_m2          1277 non-null   int64
 1   Built_area_m2          1277 non-null   int64
 2   Rooms                  1277 non-null   int64
 3   Bathrooms              1277 non-null   int64
 4   HalfBathrooms          1277 non-null   int64
 5   Parkings               1277 non-null   int64
 6   Antiguedad             1235 non-null   float64
 7   Colonia                1277 non-null   str
 8   Alcaldia               1277 non-null   str
 9   Ciudad                 1277 non-null   str
 10  Estado                 1196 non-null   str
 11  Price                  1277 non-null   int64
 12  Maintenance_cost       1277 non-null   int64
 13  Address                1274 non-null   str
 14  PropertyType           1277 non-null   str
 15  OperationType          1277 non-null   str
 16  PropertyTypeDataLayer  1277 non-null   str
 17  IsAuction              1277 non-null   bool
 18  FlagsFeatures          779 non-null    str
 19  HaveVideo              1277 non-null   bool
 20  VideoIDs               343 non-null    str
 21  Latitude               1277 non-null   float64
 22  Longitude              1277 non-null   float64
 23  PostingID              1277 non-null   int64
 24  URL                    1277 non-null   str
dtypes: bool(2), float64(3), int64(9), str(11)
memory usage: 514.5 KB

In [24]:
datos.head()

,Total_area_m2,Built_area_m2,Rooms,Bathrooms,HalfBathrooms,Parkings,Antiguedad,Colonia,Alcaldia,Ciudad,Estado,Price,Maintenance_cost,Address,PropertyType,OperationType,PropertyTypeDataLayer,IsAuction,FlagsFeatures,HaveVideo,VideoIDs,Latitude,Longitude,PostingID,URL
0,291,330,4,3,1,2,18.0,Lindavista Norte,Gustavo A. Madero,Ciudad de México,Mexico,2852000,0,Lima,Casa,venta,Casa,True,remateHipotecario,False,NaN,19.493975,-99.126019,150994073,https://www.inmuebles24.com/propiedades/clasif...
1,58,58,2,1,0,1,10.0,El Arbolillo,Gustavo A. Madero,Ciudad de México,Mexico,948560,0,5o de Río Santa María,Casa,venta,Casa,True,remateHipotecario,False,NaN,19.528917,-99.147384,151300052,https://www.inmuebles24.com/propiedades/clasif...
2,485,395,3,4,1,3,41.0,Torres Lindavista,Gustavo A. Madero,Ciudad de México,Mexico,19800000,1500,jovellanos,Casa,venta,Casa,False,NaN,False,NaN,19.507518,-99.149450,151044489,https://www.inmuebles24.com/propiedades/clasif...
3,47,47,2,1,0,1,0.0,Panamericana,Gustavo A. Madero,Ciudad de México,Mexico,2206106,1500,Norte 7-A 4934,Apartamento,venta,Departamento,False,NaN,False,NaN,19.478880,-99.144322,149411443,https://www.inmuebles24.com/propiedades/clasif...
4,77,77,2,2,0,1,4.0,Granjas Modernas,Gustavo A. Madero,Ciudad de México,Mexico,2750000,0,Palomas 43,Apartamento,venta,Departamento,False,NaN,False,NaN,19.478388,-99.103424,150923116,https://www.inmuebles24.com/propiedades/clasif...

# Correct Data type

In [25]:
datos['Antiguedad'] = datos['Antiguedad'].astype('Int64')

In [26]:
print(datos['PropertyType'].unique())
datos['PropertyType'] = datos['PropertyType'].astype('category')

<ArrowStringArray>
['Casa', 'Apartamento', 'Casa en condominio']
Length: 3, dtype: str

In [27]:
print(datos['OperationType'].unique())
datos.drop(columns=['OperationType'], inplace=True)

<ArrowStringArray>
['venta']
Length: 1, dtype: str

In [ ]:
datos['PropertyTypeDataLayer'].unique()
datos.drop(columns=['PropertyTypeDataLayer'], inplace=True)

<ArrowStringArray>
['Casa', 'Departamento', 'Casa en condominio']
Length: 3, dtype: str

In [30]:
datos['IsAuction'].unique()

array([ True, False])

In [33]:
print(datos['FlagsFeatures'].unique())
datos['FlagsFeatures'] = datos['FlagsFeatures'].astype('category')

<ArrowStringArray>
['remateHipotecario', nan, 'duenoDirecto']
Length: 3, dtype: str

## Handling Null values, imputing and droping values

In [36]:
resume = pd.DataFrame({
    'Quantity of Null Values': datos.isna().sum(),
    'Percentage of Null Values': datos.isna().mean().map(lambda x: f"{x:.2%}")
})

resume

                       Quantity of Null Values Percentage of Null Values
Total_area_m2                                0                     0.00%
Built_area_m2                                0                     0.00%
Rooms                                        0                     0.00%
Bathrooms                                    0                     0.00%
HalfBathrooms                                0                     0.00%
Parkings                                     0                     0.00%
Antiguedad                                  42                     3.29%
Colonia                                      0                     0.00%
Alcaldia                                     0                     0.00%
Ciudad                                       0                     0.00%
Estado                                      81                     6.34%
Price                                        0                     0.00%
Maintenance_cost                             0                     0.00%
Address                                      3                     0.23%
PropertyType                                 0                     0.00%
PropertyTypeDataLayer                        0                     0.00%
IsAuction                                    0                     0.00%
FlagsFeatures                              498                    39.00%
HaveVideo                                    0                     0.00%
VideoIDs                                   934                    73.14%
Latitude                                     0                     0.00%
Longitude                                    0                     0.00%
PostingID                                    0                     0.00%
URL                                          0                     0.00%

### Antiguedad
The variable **Antiguedad** is going to be analyzed and imputed if possible

In [39]:
datos['Antiguedad'].describe()

count       1235.0
mean     21.382186
std      16.515638
min            0.0
25%           10.0
50%           18.0
75%           30.0
max          100.0
Name: Antiguedad, dtype: Float64

Due to the fact that back in the day the land wasn't too expensive in the