# Initial Data Exploration

In [24]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

datos = pd.read_csv('../data/bronze/casas_gam_full2.csv')
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Total_area_m2          1277 non-null   int64
 1   Built_area_m2          1277 non-null   int64
 2   Rooms                  1277 non-null   int64
 3   Bathrooms              1277 non-null   int64
 4   HalfBathrooms          1277 non-null   int64
 5   Parkings               1277 non-null   int64
 6   Antiguedad             1235 non-null   float64
 7   Colonia                1277 non-null   str
 8   Alcaldia               1277 non-null   str
 9   Ciudad                 1277 non-null   str
 10  Estado                 1196 non-null   str
 11  Price                  1277 non-null   int64
 12  Maintenance_cost       1277 non-null   int64
 13  Address                1274 non-null   str
 14  PropertyType           1277 non-null   str
 15  OperationType          1277 non-null   str
 16  PropertyTypeDataLayer  1277 non-null   str
 17  IsAuction              1277 non-null   bool
 18  FlagsFeatures          779 non-null    str
 19  HaveVideo              1277 non-null   bool
 20  VideoIDs               343 non-null    str
 21  Latitude               1277 non-null   float64
 22  Longitude              1277 non-null   float64
 23  PostingID              1277 non-null   int64
 24  URL                    1277 non-null   str
dtypes: bool(2), float64(3), int64(9), str(11)
memory usage: 232.1 KB

In [25]:
datos.head()

,Total_area_m2,Built_area_m2,Rooms,Bathrooms,HalfBathrooms,Parkings,Antiguedad,Colonia,Alcaldia,Ciudad,...,OperationType,PropertyTypeDataLayer,IsAuction,FlagsFeatures,HaveVideo,VideoIDs,Latitude,Longitude,PostingID,URL
0,291,330,4,3,1,2,18.0,Lindavista Norte,Gustavo A. Madero,Ciudad de México,...,venta,Casa,True,remateHipotecario,False,NaN,19.493975,-99.126019,150994073,https://www.inmuebles24.com/propiedades/clasif...
1,58,58,2,1,0,1,10.0,El Arbolillo,Gustavo A. Madero,Ciudad de México,...,venta,Casa,True,remateHipotecario,False,NaN,19.528917,-99.147384,151300052,https://www.inmuebles24.com/propiedades/clasif...
2,485,395,3,4,1,3,41.0,Torres Lindavista,Gustavo A. Madero,Ciudad de México,...,venta,Casa,False,NaN,False,NaN,19.507518,-99.149450,151044489,https://www.inmuebles24.com/propiedades/clasif...
3,47,47,2,1,0,1,0.0,Panamericana,Gustavo A. Madero,Ciudad de México,...,venta,Departamento,False,NaN,False,NaN,19.478880,-99.144322,149411443,https://www.inmuebles24.com/propiedades/clasif...
4,77,77,2,2,0,1,4.0,Granjas Modernas,Gustavo A. Madero,Ciudad de México,...,venta,Departamento,False,NaN,False,NaN,19.478388,-99.103424,150923116,https://www.inmuebles24.com/propiedades/clasif...

# Correct Data type

In [26]:
datos['Antiguedad'] = datos['Antiguedad'].astype('Int64')

In [27]:
print(datos['PropertyType'].unique())
datos['PropertyType'] = datos['PropertyType'].astype('category')

<StringArray>
['Casa', 'Apartamento', 'Casa en condominio']
Length: 3, dtype: str

In [28]:
print(datos['OperationType'].unique())

<StringArray>
['venta']
Length: 1, dtype: str

In [29]:
print(datos['PropertyTypeDataLayer'].unique())

<StringArray>
['Casa', 'Departamento', 'Casa en condominio']
Length: 3, dtype: str

In [30]:
datos['IsAuction'].unique()

array([ True, False])

In [31]:
print(datos['FlagsFeatures'].unique())
datos['FlagsFeatures'] = datos['FlagsFeatures'].astype('category')

<StringArray>
['remateHipotecario', nan, 'duenoDirecto']
Length: 3, dtype: str

<hr />

## Handling Null values, imputing and Standarizing variables

In [32]:
resume = pd.DataFrame({
    'Quantity of Null Values': datos.isna().sum(),
    'Percentage of Null Values': datos.isna().mean().map(lambda x: f"{x:.2%}")
})

resume

                       Quantity of Null Values Percentage of Null Values
Total_area_m2                                0                     0.00%
Built_area_m2                                0                     0.00%
Rooms                                        0                     0.00%
Bathrooms                                    0                     0.00%
HalfBathrooms                                0                     0.00%
Parkings                                     0                     0.00%
Antiguedad                                  42                     3.29%
Colonia                                      0                     0.00%
Alcaldia                                     0                     0.00%
Ciudad                                       0                     0.00%
Estado                                      81                     6.34%
Price                                        0                     0.00%
Maintenance_cost                             0                     0.00%
Address                                      3                     0.23%
PropertyType                                 0                     0.00%
OperationType                                0                     0.00%
PropertyTypeDataLayer                        0                     0.00%
IsAuction                                    0                     0.00%
FlagsFeatures                              498                    39.00%
HaveVideo                                    0                     0.00%
VideoIDs                                   934                    73.14%
Latitude                                     0                     0.00%
Longitude                                    0                     0.00%
PostingID                                    0                     0.00%
URL                                          0                     0.00%

### Ciudad

In [33]:
print(datos['Ciudad'].unique())

<StringArray>
['Ciudad de México', 'Mexico']
Length: 2, dtype: str

### Alcaldia

In [34]:
print(datos['Alcaldia'].unique())

<StringArray>
['Gustavo A. Madero', 'Ciudad de México']
Length: 2, dtype: str

### Estado

In [35]:
print(datos['Estado'].unique())

<StringArray>
['Mexico', nan]
Length: 2, dtype: str

### Have Video

In [36]:
print(datos['HaveVideo'].unique())

[False  True]

### Video ID

In [37]:
datos['VideoIDs'].head(10)

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7    qBk7xecrX5o
8            NaN
9            NaN
Name: VideoIDs, dtype: str

### Posting ID

In [38]:
datos['PostingID'].head(5)

0    150994073
1    151300052
2    151044489
3    149411443
4    150923116
Name: PostingID, dtype: int64

### URl

In [ ]:
datos['URL'].head()

0    https://www.inmuebles24.com/propiedades/clasif...
1    https://www.inmuebles24.com/propiedades/clasif...
2    https://www.inmuebles24.com/propiedades/clasif...
3    https://www.inmuebles24.com/propiedades/clasif...
4    https://www.inmuebles24.com/propiedades/clasif...
Name: URL, dtype: str

 This is the first part o transformations and standarizations, The next thing is going to be deleting the variable which doesn't actually give crucial information. For example, we're going to delete Variables like **Alcaldia** Because all the houses from the dataset are from GAM.

 After that, we will continue with the standarizations and imputations in another notebook.

In [40]:
datos.drop(columns=['Alcaldia', 'Estado', 'Ciudad', 'OperationType','PropertyTypeDataLayer', 'VideoIDs', 'PostingID', 'URL'], inplace=True)

In [44]:
datos.to_csv('../data/bronze/staging/stg1_casas_gam_full2.csv', index=False)